#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

FRONTEND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DIR="$(cd "$FRONTEND_DIR/../DiscGolfLabs-api" && pwd)"
ENV_FILE="$FRONTEND_DIR/.env"
cd "$FRONTEND_DIR"

TOTAL_STAGES=2
TOTAL_MINUTES=12

banner "DGL test users"

stage "Create the Clerk test users" 8
open_url "https://dashboard.clerk.com/"
say "Choose the DGL application and its development instance. Do not use production."
step "Use john+clerk_test@example.com for John Doe and jane+clerk_test@example.com for Jane Doe, unless either address is already in use."
note "Clerk suppresses delivery for +clerk_test addresses. On development instances, the email code is 424242."
ask PLAYWRIGHT_FREE_EMAIL "John's Clerk email:"
[[ "$PLAYWRIGHT_FREE_EMAIL" == *"+clerk_test@"* ]] || { warn "John's email must use Clerk's +clerk_test pattern."; exit 1; }
ask PLAYWRIGHT_PAID_EMAIL "Jane's Clerk email:"
[[ "$PLAYWRIGHT_PAID_EMAIL" == *"+clerk_test@"* ]] || { warn "Jane's email must use Clerk's +clerk_test pattern."; exit 1; }
[[ "$PLAYWRIGHT_FREE_EMAIL" != "$PLAYWRIGHT_PAID_EMAIL" ]] || { warn "Use a different email for each user."; exit 1; }
step "Open Users and search by each email. If an account is missing, choose Create user and enter John Doe or Jane Doe with that email."
pause "When both users exist, open each profile and continue."
step "Copy the current Clerk user ID shown on each profile. Confirm each profile has the matching name and email. If a user was recreated, replace the saved ID; pressing Enter keeps the old one."
ask PLAYWRIGHT_FREE_CLERK_USER_ID "John's Clerk user ID:"
ask PLAYWRIGHT_PAID_CLERK_USER_ID "Jane's Clerk user ID:"
[[ "$PLAYWRIGHT_FREE_CLERK_USER_ID" != "$PLAYWRIGHT_PAID_CLERK_USER_ID" ]] || { warn "Use a different Clerk user ID for each user."; exit 1; }
write_env PLAYWRIGHT_FREE_EMAIL "$PLAYWRIGHT_FREE_EMAIL"
write_env PLAYWRIGHT_FREE_CLERK_USER_ID "$PLAYWRIGHT_FREE_CLERK_USER_ID"
write_env PLAYWRIGHT_PAID_EMAIL "$PLAYWRIGHT_PAID_EMAIL"
write_env PLAYWRIGHT_PAID_CLERK_USER_ID "$PLAYWRIGHT_PAID_CLERK_USER_ID"

stage "Set and check DGL access" 4
say "This records both Clerk identities in MongoDB, leaves John without an active enrollment, and enrolls Jane in putting-course."
say "The API's local .env must contain a working MONGODB_URI, and the putting-course course record must already exist."
if [[ ! -f "$API_DIR/.env" ]]; then
  warn "Missing $API_DIR/.env. Configure the API first, then rerun this wizard."
  exit 1
fi
if [[ ! -d "$API_DIR/node_modules/mongoose" ]]; then
  warn "API dependencies are missing. Run npm install in $API_DIR, then rerun this wizard."
  exit 1
fi
if ! confirm "Write or update the two DGL user records and Jane's putting-course enrollment in MongoDB?"; then
  say "No database changes made. The Clerk IDs and emails are saved in $ENV_FILE."
  exit 0
fi
(
  cd "$API_DIR"
  PLAYWRIGHT_FREE_EMAIL="$PLAYWRIGHT_FREE_EMAIL" \
  PLAYWRIGHT_FREE_CLERK_USER_ID="$PLAYWRIGHT_FREE_CLERK_USER_ID" \
  PLAYWRIGHT_PAID_EMAIL="$PLAYWRIGHT_PAID_EMAIL" \
  PLAYWRIGHT_PAID_CLERK_USER_ID="$PLAYWRIGHT_PAID_CLERK_USER_ID" \
    node "$FRONTEND_DIR/scripts/setup-playwright-test-users.mjs"
)

finish
